PACKAGE_NAME="thunderbolt-ibverbs"
PACKAGE_VERSION="0.2.1"

BUILT_MODULE_NAME[0]="thunderbolt_ibverbs"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KVER=${kernelver}"

AUTOINSTALL="yes"
